### ISSUE TITLE
beginner got stuck pas -i -v config,

### ISSUE THREAD

**Issue by baaoh** [minds-ai/zoom-drive-connector#27]
Hi everyone,

I have zero coding background, and I only try to learn from step-by-step tutorials such as this one.

I also will soon have 400 zoom cloud recordings to download.

I got through a lot of pain, to get to this step, but got stuck with this error, dont know what to do anymore

This is from Docker's logs, tried using CMD, now doing things in Ubuntu because I realized your code lines start with $, am super confused, please help.

 `Traceback (most recent call last):

File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main

"__main__", mod_spec)

File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code

exec(code, run_globals)

File "/usr/local/lib/python3.7/site-packages/zoom_drive_connector/__main__.py", line 136, in <module>

main()

File "/usr/local/lib/python3.7/site-packages/zoom_drive_connector/__main__.py", line 111, in main

app_config = config.ConfigInterface(os.getenv('CONFIG', '/conf/config.yaml'))

File "/usr/local/lib/python3.7/site-packages/zoom_drive_connector/configuration/configuration_interfaces.py", line 115, in __init__

self.__interface_factory()

File "/usr/local/lib/python3.7/site-packages/zoom_drive_connector/configuration/configuration_interfaces.py", line 151, in __interface_factory

raise RuntimeError(f'Configuration for section {value.__class__} failed validation step.')

RuntimeError: Configuration for section <class 'zoom_drive_connector.configuration.configuration_interfaces.DriveConfig'> failed validation step.`

**Comment by jbedorf** [comment]
Hi, it looks like there is an error parsing your configuration file, in particular the section that contains the Google Drive parts. Could you verify if your configuration file matches with what is presented in the README. And/or paste it in this issue (without the actual credentials of course).

**Comment by baaoh** [comment]
Hi, thanks for taking your time to help me

I am stuck at this step command again, dont know what im doing wrong, and the syntax is not clear to me
```
docker run -i -v //c/users/petrv/downloads/easst/downlaods/conf:/conf docker.pkg.github.com/minds-ai/zoom-drive-connector/zoom-drive-connector:1.1.0
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/zoom_drive_connector/__main__.py", line 136, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/zoom_drive_connector/__main__.py", line 111, in main
    app_config = config.ConfigInterface(os.getenv('CONFIG', '/conf/config.yaml'))
  File "/usr/local/lib/python3.7/site-packages/zoom_drive_connector/configuration/configuration_interfaces.py", line 115, in __init__
    self.__interface_factory()
  File "/usr/local/lib/python3.7/site-packages/zoom_drive_connector/configuration/configuration_interfaces.py", line 139, in __interface_factory
    dict_from_yaml = self.__load_config()
  File "/usr/local/lib/python3.7/site-packages/zoom_drive_connector/configuration/configuration_interfaces.py", line 122, in __load_config
    with open(self.file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/conf/config.yaml'
```

Also the contents of **config.yaml** which sits in C:\Users\PetrV\Downloads\EASST\downloads\conf
```
zoom:
  key: "qnPnvKEmR4m*****"
  secret: "ECzBPbJPjGHSSp******"
  username: "***@*****.com"
  delete: true
  meetings: 
   - {id: "meeting_id" , name: "Meeting Name", folder_id: "Some Google Drive Folder ID", slack_channel: "channel_name"}
   - {id: "meeting_id2" , name: "Second Meeting Name", folder_id: "Some Google Drive Folder ID2", slack_channel: "channel_name2"}
drive:
  credentials_json: "conf/credentials.json"
  client_secret_json: "conf/client_secrets.json"
slack:
  key: "xoxb-8861*****"
internals:
  target_folder: "/tmp"
```
The one other file - generated froom google cloud **client_secrets.json** is sitting in C:\Users\PetrV\Downloads\EASST\downloads\conf too.

`{"web":{"client_id":"*****","project_id":"zomiosek","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"******"}}`

**Comment by jbedorf** [comment]
Hi, before looking into the details, I noticed there is a typo in your command line:
docker run -i -v //c/users/petrv/downloads/easst/**downlaods**/conf:/conf docker.pkg.github.com/minds-ai/zoom-drive-connector/zoom-drive-connector:1.1.0

Try running it via:
`docker run -i -v //c/users/petrv/downloads/easst/downloads/conf:/conf docker.pkg.github.com/minds-ai/zoom-drive-connector/zoom-drive-connector:1.1.0
`
